CREATE DATABASE IF NOT EXISTS sqli_lab;
USE sqli_lab;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL,
  email VARCHAR(128) NOT NULL
);

DROP TABLE IF EXISTS products;
CREATE TABLE products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  price DECIMAL(10,2) NOT NULL
);

DROP TABLE IF EXISTS tracking;
CREATE TABLE tracking (
  id INT PRIMARY KEY AUTO_INCREMENT,
  tracking_id VARCHAR(128) NOT NULL
);
